### ISSUE TITLE
Pages and journals support

### ISSUE THREAD

**Issue by artjomsR** [usoonees/logseq-plugin-link-unlink#12]
It would be great to have this plugin's functionality extended to regular pages as well. Basically if I'm typing regularly on a journal / page and a matching page is detected (i.e. what would be an unlinked reference on that page), then that word would be highlighted (with a corresponding `Link` button to convert the word into an actual `[[reference]]`)

**Comment by usoonees** [comment]
You could try the [automatic-linker](https://github.com/sawhney17/logseq-automatic-linker) plugin. However, it won't highlight the links; instead, it will add them automatically.

Regarding this plugin, it uses a regex pattern like `const reStr = "(" + pageNames.join("|") + ")"` (where `pageNames` includes the current page and its aliases) to target specific words for highlighting. The issue is that `pageNames` could be too broad, potentially affecting performance, since it will include all pages for regular page and journal.

It might be a good idea to suggest adding the highlighting feature to the automatic-linker plugin itself.
